using CsTrees.SourceGenerator.Models;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CsTrees.SourceGenerator.Emitters;

internal static class BuilderExtensionEmitter
{
    internal static string Generate(string className, string ns, List<PropertyInfo> props, List<List<(string Type, string Name, string?)>> constructors)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using CsTrees.Blackboard;");
        sb.AppendLine("using CsTrees.FluentBuilder;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// TreeBuilder extension methods for {className}.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static class {className}BuilderExtensions");
        sb.AppendLine("    {");

        GenerateBuilderExtensionMethods(sb, className, props, constructors);

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    internal static void GenerateBuilderExtensionMethods(StringBuilder sb, string className, List<PropertyInfo> props, List<List<(string Type, string Name, string?)>> constructors)
    {
        // 仅对 private 构造函数生成扩展方法；调用方应保证 constructors 非空（否则由 CST006 诊断）
        foreach (var userParams in constructors)
        {
            GenerateBuilderExtensionMethod(sb, className, props, userParams);
        }
    }

    internal static void GenerateBuilderExtensionMethod(StringBuilder sb, string className, List<PropertyInfo> props, List<(string Type, string Name, string? DefaultValue)> userParams)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// Add a {className} node to the tree builder.");
        sb.AppendLine($"        /// The blackboard is automatically injected from the builder's current scope.");
        sb.AppendLine("        /// </summary>");

        sb.Append($"        public static TBuilder {className}<TBuilder>(");
        sb.AppendLine();
        sb.AppendLine($"            this TBuilder builder,");
        sb.Append($"            string name");

        // User constructor parameters (skip 'name' parameter as it's always first)
        var paramsWithoutName = userParams.Skip(1).ToList();
        foreach (var (type, name, defaultValue) in paramsWithoutName)
        {
            sb.AppendLine(",");
            sb.Append($"            {type} {name}");
            if (defaultValue is not null)
                sb.Append($" = {defaultValue}");
        }

        // Optional port key parameters
        CodeGenHelpers.AppendPortParams(sb, props);

        sb.AppendLine(")");
        sb.AppendLine("            where TBuilder : TreeBuilder<TBuilder>");
        sb.AppendLine("        {");
        sb.AppendLine("            return builder.LeafWithBlackboard(bb => {");
        sb.AppendLine($"                if (bb is null)");
        sb.AppendLine($"                    throw new System.InvalidOperationException(\"Blackboard is required for {className}. Use .WithBlackboard() to set the scope.\");");
        sb.AppendLine();
        sb.Append($"                return new {className}(");

        // Pass name parameter (named: generated ctor reorders params, so positional
        // arguments would mismatch when the user ctor has optional params)
        sb.Append("name: name");

        // Pass other user params
        foreach (var (_, name, _) in paramsWithoutName)
        {
            sb.Append($", {name}: {name}");
        }

        // Pass blackboard
        sb.Append(", blackboard: bb");

        // Pass port key params
        foreach (var prop in props)
        {
            var paramName = CodeGenHelpers.ToCamelCase(prop.PropertyName) + "Key";
            sb.Append($", {paramName}: {paramName}");
        }

        sb.AppendLine(");");
        sb.AppendLine("            });");
        sb.AppendLine("        }");
        sb.AppendLine();
    }
}
