using CsTrees.SourceGenerator.Models;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CsTrees.SourceGenerator.Emitters;

internal static class PortPartialEmitter
{
    // Full qualified type names to avoid namespace conflicts
    private const string BlackboardType = "CsTrees.Blackboard.Blackboard";
    private const string PortDeclarationType = "CsTrees.Blackboard.PortDeclaration";
    private const string AccessType = "CsTrees.Blackboard.Access";

    internal static string Generate(string className, string ns, List<PropertyInfo> props, List<List<(string Type, string Name, string?)>> constructors)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine("    {");

        // === Constructors with blackboard (one per user constructor) ===
        GenerateConstructors(sb, className, props, constructors);

        sb.AppendLine();

        // === SetupPorts method ===
        GenerateSetupPorts(sb, props);

        sb.AppendLine();

        // === GetPortDeclarations method ===
        GenerateGetPortDeclarations(sb, props);

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    internal static void GenerateConstructors(StringBuilder sb, string className, List<PropertyInfo> props, List<List<(string Type, string Name, string?)>> constructors)
    {
        // 仅对 private 构造函数生成 public 重载；无 private 构造函数时不生成（用户自行处理 SetupPorts）
        foreach (var userParams in constructors)
        {
            GenerateConstructor(sb, className, props, userParams);
        }
    }

    internal static void GenerateConstructor(StringBuilder sb, string className, List<PropertyInfo> props, List<(string Type, string Name, string? DefaultValue)> userParams)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 创建实例并自动注册端口。");
        sb.AppendLine("        /// </summary>");

        sb.Append($"        public {className}(");

        // 分离必选与可选参数。Blackboard 是必选参数，必须出现在所有可选参数之前，
        // 否则会触发 CS1737（可选参数必须位于所有必选参数之后）。
        var requiredUserParams = userParams.Where(p => p.DefaultValue is null).ToList();
        var optionalUserParams = userParams.Where(p => p.DefaultValue is not null).ToList();

        // 必选用户参数（后面至少还有 Blackboard，总是需要逗号结尾）
        foreach (var (type, name, _) in requiredUserParams)
        {
            sb.AppendLine();
            sb.Append($"            {type} {name},");
        }

        // Blackboard（必选，插入在可选参数之前）
        sb.AppendLine();
        sb.Append($"            {BlackboardType} blackboard");

        // 可选用户参数
        foreach (var (type, name, defaultValue) in optionalUserParams)
        {
            sb.AppendLine(",");
            sb.Append($"            {type} {name}");
            if (defaultValue is not null)
                sb.Append($" = {defaultValue}");
        }

        // Optional port key parameters
        CodeGenHelpers.AppendPortParams(sb, props);

        sb.Append(") : this(");

        // Chain to user constructor
        for (int i = 0; i < userParams.Count; i++)
        {
            var (_, name, _) = userParams[i];
            sb.Append(name);
            if (i < userParams.Count - 1)
                sb.Append(", ");
        }

        sb.AppendLine(")");

        sb.AppendLine("        {");
        sb.Append("            SetupPorts(blackboard");

        foreach (var prop in props)
        {
            var paramName = CodeGenHelpers.ToCamelCase(prop.PropertyName) + "Key";
            sb.Append($", {paramName}: {paramName}");
        }

        sb.AppendLine(");");
        sb.AppendLine("        }");
    }

    internal static void GenerateSetupPorts(StringBuilder sb, List<PropertyInfo> props)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 在 Blackboard 上注册所有端口。");
        sb.AppendLine("        /// 必须在构造后、首次 Tick 前调用。");
        sb.AppendLine("        /// </summary>");
        sb.Append($"        public void SetupPorts({BlackboardType} blackboard");

        foreach (var prop in props)
        {
            var paramName = CodeGenHelpers.ToCamelCase(prop.PropertyName) + "Key";
            sb.AppendLine(",");
            sb.Append($"            string? {paramName} = null");
        }

        sb.AppendLine(")");

        sb.AppendLine("        {");

        foreach (var prop in props)
        {
            var paramName = CodeGenHelpers.ToCamelCase(prop.PropertyName) + "Key";
            var grantMethod = prop.Access switch
            {
                "Read" => "GrantRead",
                "Write" => "GrantWrite",
                "ExclusiveWrite" => "GrantExclusiveWrite",
                _ => "GrantWrite"
            };

            sb.AppendLine($"            {prop.PropertyName} = blackboard.{grantMethod}<{prop.ValueType}>(this, {paramName} ?? \"{CodeGenHelpers.EscapeString(prop.DefaultKey)}\");");
        }

        sb.AppendLine("        }");
    }

    internal static void GenerateGetPortDeclarations(StringBuilder sb, List<PropertyInfo> props)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取所有端口的声明信息。");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static IReadOnlyDictionary<string, {PortDeclarationType}> GetPortDeclarations()");
        sb.AppendLine("        {");
        sb.AppendLine($"            return new Dictionary<string, {PortDeclarationType}>");
        sb.AppendLine("            {");

        foreach (var prop in props)
        {
            sb.AppendLine($"                [\"{CodeGenHelpers.EscapeString(prop.PropertyName)}\"] = new {PortDeclarationType}(\"{CodeGenHelpers.EscapeString(prop.DefaultKey)}\", {prop.ValueTypeRef}, {AccessType}.{prop.Access}),");
        }

        sb.AppendLine("            };");
        sb.AppendLine("        }");
    }
}
