using CsTrees.SourceGenerator.Models;
using System.Linq;
using System.Text;

namespace CsTrees.SourceGenerator.Emitters;

/// <summary>
/// 为实现 IBehaviourCatalog&lt;TCatalog&gt; 的 partial TreeBuilder 子类生成预设构建方法。
/// TCatalog 中每个 public 工厂方法（返回 Behaviour 子类）对应一个 public 实例方法，
/// 方法体通过 Catalog 属性调用工厂并挂到树：
/// 含 blackboard 参数的用 LeafWithBlackboard（作用域 blackboard 注入工厂），
/// 不含的用 Leaf。
/// </summary>
internal static class TreeBuilderSubclassEmitter
{
    internal static string Generate(TreeBuilderSubclassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using CsTrees.FluentBuilder;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }

        // 不写可访问性，由用户 partial 部分决定（避免 internal/public 冲突）
        sb.AppendLine($"    partial class {info.ClassName}");
        sb.AppendLine("    {");

        for (int i = 0; i < info.Methods.Count; i++)
        {
            GenerateMethod(sb, info.ClassName, info.Methods[i]);
            if (i < info.Methods.Count - 1)
                sb.AppendLine();
        }

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    internal static void GenerateMethod(StringBuilder sb, string className, DeclMethodInfo method)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// Add a {method.MethodName} node (generated, delegates to the private preset).");
        sb.AppendLine("        /// </summary>");

        // 生成方法签名：跳过 blackboard 参数，保留其余（含默认值）
        var sigParams = method.Parameters.Where(p => !p.IsBlackboard).ToList();

        sb.Append($"        public {className} {method.MethodName}(");
        if (sigParams.Count == 0)
        {
            sb.AppendLine(")");
        }
        else
        {
            sb.AppendLine();
            for (int i = 0; i < sigParams.Count; i++)
            {
                var p = sigParams[i];
                sb.Append($"            {p.Type} {p.Name}");
                if (p.DefaultValue is not null)
                    sb.Append($" = {p.DefaultValue}");
                if (i < sigParams.Count - 1)
                    sb.AppendLine(",");
                else
                    sb.AppendLine();
            }
            sb.AppendLine("        )");
        }

        sb.AppendLine("        {");

        bool hasBlackboard = method.Parameters.Any(p => p.IsBlackboard);
        if (hasBlackboard)
        {
            sb.AppendLine("            return LeafWithBlackboard(bb => {");
            sb.AppendLine("                if (bb is null)");
            sb.AppendLine($"                    throw new System.InvalidOperationException(\"Blackboard is required for {method.MethodName}. Use .WithBlackboard() to set the scope.\");");
            sb.AppendLine();
            sb.Append($"                return Catalog.{method.MethodName}(");
            AppendCallArgs(sb, method);
            sb.AppendLine(");");
            sb.AppendLine("            });");
        }
        else
        {
            // 无 blackboard 参数：工厂方法不依赖作用域 blackboard，直接用 Leaf 挂到树
            sb.AppendLine("            return Leaf(() => {");
            sb.Append($"                return Catalog.{method.MethodName}(");
            AppendCallArgs(sb, method);
            sb.AppendLine(");");
            sb.AppendLine("            });");
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// 按声明方法的参数顺序生成调用参数：blackboard 位置传 bb，其余传同名生成方法参数。
    /// </summary>
    private static void AppendCallArgs(StringBuilder sb, DeclMethodInfo method)
    {
        for (int i = 0; i < method.Parameters.Count; i++)
        {
            if (i > 0)
                sb.Append(", ");
            if (method.Parameters[i].IsBlackboard)
                sb.Append("bb");
            else
                sb.Append(method.Parameters[i].Name);
        }
    }
}
