using System.Collections.Generic;
using System.Text;
using CsTrees.MEAI.SourceGenerator.Models;

namespace CsTrees.MEAI.SourceGenerator.Emitters;

/// <summary>
/// 为继承 BuildToolsBase&lt;TBuilder&gt; 的 partial 类生成工具调用方法。
/// 每个 Catalog 工厂方法对应一个同步方法：检查 builtTree 状态后委托给 Builder 的
/// 同名 SG 生成方法，成功返回带树预览的 ToolResult，失败返回错误 ToolResult。
/// 方法与参数保留 [Description]，供后续 AIFunctionFactory 注册工具时提取。
/// </summary>
internal static class BuildToolsEmitter
{
    internal static string Generate(BuildToolsClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using CsTrees.MEAI;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }

        // 不写可访问性，由用户 partial 部分决定（避免 internal/public 冲突）
        sb.AppendLine($"    partial class {info.ClassName}");
        sb.AppendLine("    {");

        for (int i = 0; i < info.Methods.Count; i++)
        {
            GenerateMethod(sb, info.Methods[i]);
            sb.AppendLine();
        }

        GenerateToolsProperty(sb, info);

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    internal static void GenerateMethod(StringBuilder sb, ToolMethodInfo method)
    {
        if (!string.IsNullOrEmpty(method.Description))
        {
            sb.AppendLine($"        [Description(\"{EscapeString(method.Description)}\")]");
        }

        sb.Append($"        public ToolResult {method.MethodName}(");
        AppendSignature(sb, method.Parameters);
        sb.AppendLine("        {");
        AppendBody(sb, method);
        sb.AppendLine("        }");
    }

    /// <summary>
    /// 生成 Delegate 数组属性 Tools，聚合基类工具方法、宿主自身工具方法与生成的目录工具方法，
    /// 便于外界统一获取所有工具方法的委托。每个方法组按其签名转换为对应委托类型（Func&lt;...&gt;）。
    /// </summary>
    private static void GenerateToolsProperty(StringBuilder sb, BuildToolsClassInfo info)
    {
        var names = new List<string>();
        foreach (var n in info.BaseToolMethods) AddUnique(names, n);
        foreach (var n in info.OwnToolMethods) AddUnique(names, n);
        foreach (var m in info.Methods) AddUnique(names, m.MethodName);

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 所有工具方法的委托数组（含基类方法、宿主自身方法与生成的目录方法），便于外界统一获取与注册。");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public System.Delegate[] Tools => new System.Delegate[]");
        sb.AppendLine("        {");
        for (int i = 0; i < names.Count; i++)
        {
            sb.Append($"            {names[i]}");
            sb.AppendLine(i < names.Count - 1 ? "," : string.Empty);
        }
        sb.AppendLine("        };");
    }

    /// <summary>按名去重后追加到列表。</summary>
    private static void AddUnique(List<string> list, string name)
    {
        if (!list.Contains(name))
            list.Add(name);
    }

    /// <summary>
    /// 生成参数列表：单参数同行，多参数换行；参数带 [Description] 和默认值。
    /// </summary>
    private static void AppendSignature(StringBuilder sb, List<ToolParamInfo> parameters)
    {
        if (parameters.Count == 0)
        {
            sb.AppendLine(")");
            return;
        }

        sb.AppendLine();
        for (int i = 0; i < parameters.Count; i++)
        {
            var p = parameters[i];
            if (!string.IsNullOrEmpty(p.Description))
                sb.AppendLine($"            [Description(\"{EscapeString(p.Description)}\")]");
            sb.Append($"            {p.Type} {p.Name}");
            if (p.DefaultValue is not null)
                sb.Append($" = {p.DefaultValue}");
            if (i < parameters.Count - 1)
                sb.AppendLine(",");
            else
                sb.AppendLine();
        }
        sb.AppendLine("        )");
    }

    private static void AppendBody(StringBuilder sb, ToolMethodInfo method)
    {
        AppendBody(sb, method.MethodName, GetSuccessMessage(method), method.Parameters);
    }

    private static void AppendBody(StringBuilder sb, string methodName, string successMessage, List<ToolParamInfo> parameters)
    {
        sb.AppendLine("            if (builtTree is not null)");
        sb.AppendLine("                return Error(\"树已构建，不能再修改。\");");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.Append($"                builder.{methodName}(");
        AppendCallArgs(sb, parameters);
        sb.AppendLine(");");
        sb.AppendLine($"                return FormatStatus(\"{EscapeString(successMessage)}\");");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (System.InvalidOperationException ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                return Error(ex.Message);");
        sb.AppendLine("            }");
    }

    /// <summary>
    /// 按生成签名的参数顺序生成调用参数（同名传递）。
    /// </summary>
    private static void AppendCallArgs(StringBuilder sb, List<ToolParamInfo> parameters)
    {
        for (int i = 0; i < parameters.Count; i++)
        {
            if (i > 0)
                sb.Append(", ");
            sb.Append(parameters[i].Name);
        }
    }

    private static string GetSuccessMessage(ToolMethodInfo method)
    {
        return method.NodeType switch
        {
            ToolNodeType.Composite => $"已打开 {method.MethodName} 复合节点作用域",
            ToolNodeType.Decorator => $"已打开 {method.MethodName} 装饰器作用域",
            _ => $"已添加 {method.MethodName} 叶子节点"
        };
    }

    private static string EscapeString(string? s)
    {
        if (s is null) return string.Empty;
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
