<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.0.1</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>Just another behaviour tree framework for .NET</Description>
    <Authors>FishmanTheMurloc(with AI)</Authors>
    <RepositoryUrl>https://github.com/FishmanTheMurloc/CsTrees</RepositoryUrl>
    <PackageTags>behaviour-tree;btree;py_trees</PackageTags>
    <PackageProjectUrl>https://github.com/FishmanTheMurloc/CsTrees</PackageProjectUrl>
	  
  </PropertyGroup>
	
  <ItemGroup>
    <None Include="..\CsTrees.SourceGenerator\bin\$(Configuration)\netstandard2.0\CsTrees.SourceGenerator.dll"
		  Pack="true"
		  PackagePath="analyzers/dotnet/cs/"
          Visible="false"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>